notifications:
  email:
    - steven24205@gmail.com
    - P76061467@gmail.com
  on_success: change # default: change
  on_failure: always # default: always


os:
  - linux
  - osx
  - windows
script:
  - sleep 3
  - exit 1
