notifications:
  email:
    - steven24205@gmail.com
    - P76061467@gmail.com
  on_success: never # default: change
  on_failure: change # default: always

sudo: false
dist: trusty
language: c
os:
  - linux
  - osx
  - windows
matrix:
  script:
    - sudo sleep 1
    - exit 1
  script:
    - echo "test"
