name: "MySQL"
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
dist:
  - trusty
  - xenial
sudo:
  - required
  - true
  - false
matrix:
  include:
    - sudo: false 
      dist: trusty
      php:
      - 5.4
      - 5.5
      - 7.0
      - 7.1
    - sudo: required 
      dist: trusty
      php:
      - 5.4
      - 5.5
      - 7.0
      - 7.1
    - dist: xenial
      sudo: required
      php:
      - 5.4
      - 5.5
      - 7.0
      - 7.1      

services:
  - mysql
env:
  - DB=mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
before_script:
  #- mysql -e 'create database test;'
  - mysql_upgrade
  - mysql -u root -e "CREATE DATABASE test;"
  #- mysql -u root -e "CREATE USER 'travis'@'%' IDENTIFIED BY 'password';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost';";
script:
  - php try_mysql.php
