name: LAMP
stage: "lamp"
language: php
php:
    - 5.6
    - 7.1
services:
  - mysql
env:
  - DB=mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
before_script:
    - sudo apt-get install apache2
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
    - sudo service apache2 restart
    - mysql -u root -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost';";
    - bin/vendors install
    - app/console doctrine:database:create
    - app/console doctrine:schema:update --force
    - app/console doctrine:fixtures:load
script:
    - curl -L 127.0.0.1
after_failure:
    - sleep 3
