language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
services:
  - mysql

dist: trusty

sudo: required

before_script:
  - mysql -e 'create database antvel;' 
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pnew_password
  - sudo service mysql restart
script:
  - php try_mysql.php
