name: "MySQL"
language: php


php:
  - 5.4
  - 5.5
  - 7.0
  - 7.1
matrix:
  include:
    - sudo: false 
      dist: trusty
    - sudo: required 
      dist: trusty
    - dist: xenial
      sudo: required

services:
  - mysql
env:
  - DB=mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
before_script:
  #- mysql -e 'create database test;'
  - mysql_upgrade
  - mysql -u root -e "CREATE DATABASE test;"
  #- mysql -u root -e "CREATE USER 'travis'@'%' IDENTIFIED BY 'password';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost';";
script:
  - php try_mysql.php
