dist: trusty

sudo: false

matrix:
  include:
  - language: php
    php:
      - 5.4
      - 5.6
      - 7.0
      - 7.1
    services:
      - mysql
    env:
      - DB=mysql
    addons:
      apt:
        sources:
          - mysql-5.7-trusty
        packages:
          - mysql-server
    before_script:
      - mysql -e 'create database test;'
    script:
      - php try_mysql.php
  - language: python
    python:
        - "2.7"
    services:
        - docker
    before_install:
        - docker pull selenium/node-firefox:3.8.1-francium
        - docker pull selenium/hub:3.8.1-francium
        - docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.8.1-francium
        - docker run -d --link selenium-hub:hub --name selenium-node-firefox -v /dev/shm:/dev/shm selenium/node-firefox:3.8.1-francium
    # command to install dependencies
    install:
        - pip install -r requirements.txt
    script:
        - python tests.py 

  - language: python
    python:
        - "2.7"
        - 3.5
    addons: # get google-chrome-stable
        - chrome: stable
    before_script: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
        - wget -N https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - sudo mv -f ~/chromedriver /usr/local/share/
        - sudo chmod +x /usr/local/share/chromedriver
        - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    # command to install dependencies
    install:
        - pip install -r requirements.txt
    script:
        - whereis google-chrome-stable
        - whereis chromedriver
        - ls /usr/local/share/chromedriver
        - ls /usr/local/bin/chromedriver
        - python tests.py
