notifications:
  email:
    - steven24205@gmail.com
    - P76061467@gmail.com
  on_success: never # default: change
  on_failure: change # default: always

sudo: false
dist: trusty
language: php
os:
  - linux
  - osx
  - windows
script:
  - exit 0
