language: c

matrix:
  include:
  - dist: precise
    sudo: required
  - dist: trusty
    sudo: true
  - sudo: required
    dist: trusty
  - dist: xenial
  - os: osx	
  - os: windows
    
script:
  - echo "ok?"
