language: python
python:
  - 2.7
  - 3.5
apt:
  packages:
    - git
cache: pip
before_install: echo "1"
install:
  - pip install -r requirements.txt
  - echo "2"
before_script: echo "3"
script: echo "4"
before_cache:
  - pip uninstall selenium
  - echo "5"
after_success: echo "6"
after_failure: echo "7"
after_script: echo "8"
