language: php
dist: trusty
sudo: 
  - false
  - required
php:
  - 5.4
  - 5.5
  - 7.0
  - 7.1

matrix:
  include:
  - dist: precise
    sudo: false
    php: 5.6
  - dist: xenial
    php: 5.6
  exclude:
  - sudo: false
    php: 7.1
script:
- echo "script"
