language: php
env:
- DB=mongodb
- DB=redis
- DB=mysql
sudo: 
  - false
  - required
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
# env: # important!
matrix:
  fast_finish: true
  include:
  - os: windows
    sudo: false
    php: 5.6
    env: KEY=VALUE
  - os: ios
    php: 5.6
  exclude:
  - sudo: false
    php: 7.1
  allow_failures:
  - os: windows
    env: KEY=VALUE
  - php: 5.6
script:
- echo "script"
